"""create initial table

Revision ID: 783886314401
Revises: c79333bbc692
Create Date: 2026-02-07 13:36:47.336406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783886314401'
down_revision: Union[str, Sequence[str], None] = 'c79333bbc692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('isCompleted', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'isCompleted')
    # ### end Alembic commands ###
