"""create initial table

Revision ID: 96fdd068681d
Revises: 783886314401
Create Date: 2026-02-07 13:46:33.496511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fdd068681d'
down_revision: Union[str, Sequence[str], None] = '783886314401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_completed', sa.String(), nullable=False))
    op.drop_column('task', 'isCompleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('isCompleted', sa.VARCHAR(), nullable=False))
    op.drop_column('task', 'is_completed')
    # ### end Alembic commands ###
